apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helloworld
  namespace: helloworld
  targetNamespace: helloworld
spec:
  interval: 5m
  chart:
    spec:
      chart: ./appManifests/helloworld
      sourceRef:
        kind: GitRepository
        name: eks-infra
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/damekarv/helloworld
      tag: v0.4.0 # Updated by CI
    imagePullSecrets:
      - name: helloworld-ghcr-pat
    replicaCount: 1
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
