apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helloworld
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./appManifests/helloworld
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/damekarv/helloworld
      tag: v0.4.0 # Updated by CI
    replicaCount: 2
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
