apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ include "helloworld.fullname" . }}
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "helloworld.fullname" . }}
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rolled back (default 600s)
  progressDeadlineSeconds: 60
  service:
    # service port number
    port: {{ .Values.service.port }}
    # container port number or name (optional)
    targetPort: {{ .Values.service.port }}
  analysis:
    # schedule interval (default 60s)
    interval: 1m
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 10
    metrics:
      - name: request-success-rate
        # minimum req success rate (non 5xx responses)
        # percentage (0-100)
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration
        # maximum req duration P99
        # milliseconds
        thresholdRange:
          max: 500
        interval: 1m
